### ISSUE TITLE
Let user filter mob by level

### ISSUE THREAD

**Issue by arxdsilva** [edualb/Tibro#10]
While using the bot it was clear that it can get messy when dealing with common mobs (that can have multiple levels) because it can sometimes return multiple mobs when only 1 is wanted. We should implement a second argument in the bot call that allows the user to specify a level of that mob so it can return only 1 entry.

**Comment by edualb** [comment]
in Ragnarok database site exists a level filter but it is not a level absolutly, it is a level range. For example: 

> 100~170

 or 

> 20~60. 

We can create a absolutly level which go this level to 175. For example: 
> 100~175 

or 

> 20~175
