### ISSUE TITLE
Help command

### ISSUE THREAD

**Issue by arxdsilva** [edualb/Tibro#11]
We should have a flag (‘-h’ as an example) that returns a small guide on how to use the bot for a new user.

**Comment by edualb** [comment]
@arxdsilva 
I created a function that when write "!lib" shows all bot commands. Anything else to implement in this function? Do I change the '!lib' command to '-h' command?

**Comment by arxdsilva** [comment]
it'd be better something like '-h' or '!help' or '!h'

**Comment by edualb** [comment]
@arxdsilva commands was switched of '!lib' to '!help' or '!h'. We can closed this issue?

**Comment by arxdsilva** [comment]
not before we merge the branch PR :D
