### ISSUE TITLE
CI

### ISSUE THREAD

**Issue by arxdsilva** [edualb/Tibro#4]
O caminho pra gente se certificar que nossos testes estao em ordem eh adicionar um sistema de integracao continua para verificar a cada commit se os testes estao passando. Geralmente eu uso o [Travis](travis-ci.org) e aparentemente para repositorios JS eh bem tranquilo de se fazer a [integracao](https://docs.travis-ci.com/user/languages/javascript-with-nodejs/). 

Nao tenho permissao pra adicionar o repositorio, mas vou commitar o arquivo de configuracao.

**Comment by arxdsilva** [comment]
https://github.com/edualb/Tibro/commit/b452995972c0b2be9b64e4a19f55a838eb27987d

**Comment by edualb** [comment]
Show!!! Já ouvi falar, mas nunca fiz... Olhando de relance parece ser bem tranquilo mesmo... Não vou conseguir pegar hoje, mas amanhã vou colocar o repositório no Travis CI =) 
GoGo!

**Comment by edualb** [comment]
Acredito que tenha funcionado:
![image](https://user-images.githubusercontent.com/39157101/50029191-38c1a100-ffd9-11e8-970b-c4180f85fcb8.png)
eu só não sei como que faço para você receber uma mensagem caso o teste falhe @arxdsilva. Você sabe como que faz?

* Edit 1
Acabei de descobrir que da pra ver se o teste falhou no git hehe

**Comment by arxdsilva** [comment]
Tu recebe e-mail quando falha

**Comment by edualb** [comment]
Já está funcionando. Vou fechar essa Issue.
