### ISSUE TITLE
Discord aceita somente imagens com URL.

### ISSUE THREAD

**Issue by edualb** [edualb/Tibro#6]
Temos que abrir um servidor que faça upload das imagens...

Fonte: [StackOverflow](https://stackoverflow.com/questions/51199950/how-do-i-use-a-local-image-on-a-discord-js-rich-embed)

**Comment by edualb** [comment]
Não é uma solução boa, está pegando a a imagem localmente, por enquanto é a solução que achei.

**Comment by arxdsilva** [comment]
da forma que ta pode ser que cause problemas, com varias requisicoes escrevendo no mesmo arquivo, deve ter alguma forma de vc enviar oq fez de download do buffer direto pro discord, mesmo pelo `discord.Attachment`

**Comment by arxdsilva** [comment]
https://discord.js.org/#/docs/main/stable/class/Attachment
https://discord.js.org/#/docs/main/stable/typedef/BufferResolvable

pode ser simplesmente a URL pro arquivo tb, assim vc evita escrever localmente

**Comment by edualb** [comment]
@arxdsilva Para isso precisamos abrir um servidor, pois a imagem que se pega do site é em data URI e o discordJS não aceita data URI...

**Comment by arxdsilva** [comment]
Acredito que da forma que esta ja podemos fechar essa issue, oq vc acha @edualb ?

**Comment by edualb** [comment]
Acho válido @arxdsilva ! Fechando...
