### ISSUE TITLE
README: Add status badges

### ISSUE THREAD

**Issue by arxdsilva** [edualb/Tibro#8]
references:
license: [![LICENSE](https://img.shields.io/badge/license-MIT-orange.svg)](LICENSE)
travis: [![Travis Build Status](https://api.travis-ci.org/XML-Comp/XML-Comp.svg?branch=master)](https://travis-ci.org/XML-Comp/XML-Comp)

**Comment by edualb** [comment]
@arxdsilva Tem mais algum badge para adicionar?

**Comment by arxdsilva** [comment]
Show, acredito que por enquanto nao, vou aproveitar pra fechar a issue
